### ISSUE TITLE
BCW-00001 Инициализация laravel проекта

### ISSUE THREAD

**Issue by Atevann** [Atevann/botec#8]
1. Склонировать репозиторий
2. Пройти по шагам и создать новый laravel проект https://laravel.com/docs/10.x/installation (если будешь пробовать распаковать сразу в папку репозитория, то может будет ругаться что папка не пустая. Попробуй создать новую пустую папку, создать в ней laravel проект и после этого скопипастить файлы в репозиторий)
3. Убедиться что laravel установился корректно (открывается приветственная страница по url)
4. Закоммитить и оформить PR

**Comment by Amrik97** [comment]
Инициализировал laravel проект
